author = "CreatureSurvive"
baseURL = "https://creaturesurvive.github.io/repo"
builddrafts = false
canonifyurls = true
contentdir = "content"
googleAnalytics = "UA-119551439-1"
languageCode = "en-US"
layoutdir = "layouts"
pluralizelisttitles = false
publishdir = "public"
publishBranch = "gh-pages"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "b2"
pygmentsuseclasses = true
theme = "cocoa"
title = "CreatureSurvive"

[[menu.main]]
    identifier = "packages"
    name = "Packages"
    url = "packages/"
    weight = -100

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "about/"
    weight = -110
[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "blog/"
    weight = -120
[params]
    author = "CreatureSurvive"
    avatar = "img/CS_Logo.svg"
    cachebuster = true
    dateform = "Jan 1, 2018"
    description = "Don't panic"
    faviconfile = "img/favicon.ico"

    gitalk = false
    gitalk_admin = "CreatureSurvive"
    gitalk_clientid = "58099ad49b44018d2e74"
    gitalk_clientsecret = "901f2522f31f1ac57486c1f7c7a2c8d442aecea7"
    gitalk_owner = "CreatureSurvive"
    gitalk_repo = "website_comments"

    disqus = false
    disqusShortname = "CreatureCoding"

    highlightjs = true
    highlightjslanguages = ["go"]
    highlightjsstyle = "ir-black"
    
    i18n_flags = false
    include_rss = true
    keywords = "blog,developer,cydia,repo"
    lang = "en"
    latestpostscount = 15
    noshowreadtime = false
    selfintro = ""
	
    # Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.
	
    # Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = "CreatureCoding"
    # 404 page
	title404 = ""
	subtitle404 = ""
    # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"

[social]
    twitter = "https://www.twitter.com/CreatureSurvive"
    github = "https://www.github.com/CreatureSurvive"
    reddit = "https://www.reddit.com/u/CreatureSurvive"
    envelope = "support@creaturecoding.com"


[permalinks]
    blog = "blog/:slug/"
